### ISSUE TITLE
Invoke-VulnAD : 无法将“Invoke-VulnAD”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路 径，请确保路径正确，然后再试一次。

### ISSUE THREAD

**Issue by zxc7528064** [WazeHell/vulnerable-AD#16]
Test OS :  Windows 2016

Invoke-VulnAD : 无法将“Invoke-VulnAD”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路
径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ Invoke-VulnAD -UsersLimit 100 -DomainName "tdslab.local"
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-VulnAD:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

![image](https://user-images.githubusercontent.com/45315211/188345523-cd862cc1-95f8-40ed-b773-4759ff1599a9.png)

**Comment by mclkov** [comment]
Hello, try "Import-Module vulnad.ps1"

**Comment by zxc7528064** [comment]
@mclkov thanks you , I resolve it .

**Comment by Pc70035** [comment]
Con que #"√}∆
