### ISSUE TITLE
Unexpected token on Windows Server 2008 R2

### ISSUE THREAD

**Issue by tieupham267** [WazeHell/vulnerable-AD#2]
It looks like an error with Windows Server 2008 R2 when running IEX script

Invoke-Expression: Unexpected token 'â-^â-^â'â-^â-^â'' in expression or statement.
At line:1 char:4
+ IEX <<<< ((new-object net.webclient).downloadstring("https://raw.githubusercontent.com/wazehell/vulnerable-AD/master/
vulnad.ps1"));
    + CategoryInfo          : ParserError: (â-^â-^â'â-^â-^â':String) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand

![iex](https://user-images.githubusercontent.com/10756339/91662785-cd9e6200-eb0e-11ea-8531-8a5a60e00c07.PNG)

**Comment by WazeHell** [comment]
download the script and use Import-Module and check if u got it
