### ISSUE TITLE
not getting installed. Pls help

### ISSUE THREAD

**Issue by jabriyel** [WazeHell/vulnerable-AD#5]
PS C:\Users\Administrator> IEX((new-object net.webclient).downloadstring("https://raw.githubusercontent.com/wazehell/vulnerable-AD/master/vulnad.ps1"));
IEX : At line:24 char:46
+ ...   $banner+= $Global:Spacing + 'â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘   â–ˆâ– ...
+                                                ~~~~~~~~~~~~~~~~~~
Unexpected token 'â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘' in expression or statement.
At line:25 char:46
+ ...   $banner+= $Global:Spacing + 'â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘   â–ˆâ– ...
+                                                ~~~~~~~~~~~~~~~~~~
Unexpected token 'â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘' in expression or statement.
At line:258 char:37
+     Write-Good "SMB Signing Disabled"
+                                     ~
The string is missing the terminator: ".
At line:20 char:21
+ function ShowBanner {
+                     ~
Missing closing '}' in statement block or type definition.
At line:1 char:1
+ IEX((new-object net.webclient).downloadstring("https://raw.githubuser ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by qukuid** [comment]
The problem is in the function ShowBanner. If you copy it and delete this, it will work!

**Comment by fahadalmulhim96** [comment]
I Have get the same error what should I do? 
and what do you mean that the error in the function ShowBanner?
and what do you mean by copy it and delete it?

**Comment by superuser5** [comment]
lines 23-29 not encoded properly and causing error, so you can delete them and run script again.

**Comment by qukuid** [comment]
> I Have get the same error what should I do?
> and what do you mean that the error in the function ShowBanner?
> and what do you mean by copy it and delete it?

Just download the script, open it with Notepad or any other editor. Then delete the all the lines between 20 and 34. Including those two. Save and run the script.

**Comment by b3nj1-1** [comment]
Try to copy the script in notepad and save
