### ISSUE TITLE
Install Errors - Banner and Validation Errors

### ISSUE THREAD

**Issue by forensic65x** [WazeHell/vulnerable-AD#6]
I'm getting errors that appear to be triggered by the special characters in the banner.  

I trimmed the banner and still getting ParameterArgumentValidationErrors.. 

If I run it using version 3.0 of powershell it appears some modules are running (PasswordSpray, DCSync, etc) but others are not.

This is a fresh install of 2016 setup as a Primary DC.

**Comment by devl00p** [comment]
I solved the `ParserError` by saving the vulnad.ps1 script, opening it within Notepad++, changing the file encoding (`Encoding > UTF-8-BOM`) and saving it.

Then I was able to import it (`Import-Module .\vulnad.ps1`) and successfully lanch the last command (`Invoke-VulnAD`)

**Comment by b3nj1-1** [comment]
Try to save with notepad

**Comment by synap5e** [comment]
To run this just from powershell, the following should work
```
(New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/wazehell/vulnerable-AD/master/vulnad.ps1") | Out-File -Encoding ascii vulnad.ps1
Import-Module .\vulnad.ps1
Invoke-VulnAD
```
